-- ============================================================================
-- Module: send-testing
-- Migration: 003_provision_rpcs
-- Description: Provisioning primitives for the synthetic test population.
--
-- WHY NOT people_import_batch: the platform's bulk-import RPC is SECURITY
-- DEFINER gated on public.is_admin(), which resolves auth.uid() from the
-- caller's JWT. The provisioning job runs in a background worker on a
-- service-role client, where auth.uid() is NULL, so that RPC would raise
-- 'admin only' on every call. These functions do the same work with an
-- authorisation rule a worker can actually satisfy.
--
-- The safety property that replaces the is_admin() gate is stronger for this
-- use case: every function here is HARD-LIMITED to addresses at the caller-
-- supplied test domain and to rows carrying acquisition_source='send_testing'.
-- They cannot read, modify, or delete a real person under any argument.
--
-- See spec-send-testing-module.md §4.2.
-- ============================================================================

-- Caller guard. These functions are SECURITY DEFINER and write to public.people,
-- so they must not be callable by any logged-in user through PostgREST's
-- /rest/v1/rpc/... — that route bypasses the module's Express admin middleware
-- entirely. Only the service-role worker/API client or a real admin may call
-- them. Grants at the bottom of this file are narrowed to match; this check is
-- the belt to that braces, so a future re-grant cannot silently open them.
CREATE OR REPLACE FUNCTION public.send_test_assert_caller()
RETURNS void
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Two independent ways of recognising the service client, because getting
  -- this wrong in the strict direction breaks provisioning outright: PostgREST
  -- both SETs LOCAL ROLE to service_role and puts role in the JWT claims, and
  -- either one alone is sufficient evidence.
  IF current_user = 'service_role' OR COALESCE(auth.role(), '') = 'service_role' THEN
    RETURN;
  END IF;
  -- A genuine admin session.
  IF public.is_admin() THEN
    RETURN;
  END IF;
  RAISE EXCEPTION 'send-testing: admin or service role required';
END;
$$;

-- Guard: a test domain must look like a domain and must not be a bare public
-- suffix. Callers pass it from module config; this is the last line of defence
-- before any write touches public.people.
CREATE OR REPLACE FUNCTION public.send_test_assert_domain(p_domain text)
RETURNS text
LANGUAGE plpgsql
IMMUTABLE
AS $$
BEGIN
  IF p_domain IS NULL OR p_domain = '' THEN
    RAISE EXCEPTION 'send-testing: inbound domain is not configured';
  END IF;
  IF p_domain !~ '^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$' THEN
    RAISE EXCEPTION 'send-testing: invalid inbound domain %', p_domain;
  END IF;
  -- A single-label domain, or one with no dot, would widen the LIKE guards
  -- below to far more than the test population.
  IF array_length(string_to_array(p_domain, '.'), 1) < 2 THEN
    RAISE EXCEPTION 'send-testing: inbound domain % is too broad', p_domain;
  END IF;
  RETURN lower(p_domain);
END;
$$;

-- 1. Provision one chunk ------------------------------------------------------
-- p_rows: [{email, attributes:{first_name,last_name,timezone,is_test,...}}, ...]
-- generated by the worker so name/timezone assignment stays deterministic in
-- one place (seeded from the sequence number) and testable in TypeScript.
CREATE OR REPLACE FUNCTION public.send_test_provision_batch(
  p_rows    jsonb,
  p_domain  text,
  p_list_id uuid
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_domain   text := public.send_test_assert_domain(p_domain);
  v_created  integer := 0;
  v_subbed   integer := 0;
BEGIN
  PERFORM public.send_test_assert_caller();
  IF p_list_id IS NULL THEN
    RAISE EXCEPTION 'send-testing: target list id is required';
  END IF;

  WITH raw AS (
    SELECT lower(trim(r->>'email')) AS email,
           COALESCE(r->'attributes', '{}'::jsonb) AS attrs
    FROM jsonb_array_elements(p_rows) r
  ),
  valid AS (
    -- Only ever addresses at the test domain. Anything else is silently
    -- dropped rather than raising, so one malformed row cannot fail a chunk.
    SELECT * FROM raw
    -- Local part must be the st-<sequence> scheme, not merely "some address at
    -- the test domain": every other part of the module parses that shape, and
    -- the receiver only accepts it.
    WHERE email ~ '^st-[0-9]{6,}@[^@\s]+\.[^@\s]+$'
      AND email LIKE '%@' || v_domain
  ),
  dedup AS (
    SELECT DISTINCT ON (email) email, attrs FROM valid
  ),
  inserted AS (
    INSERT INTO public.people (email, contact_kind, acquisition_source, attributes)
    SELECT d.email, 'member', 'send_testing', d.attrs
    FROM dedup d
    ON CONFLICT (email) DO NOTHING
    RETURNING id, email
  ),
  -- Subscribe both the rows just created and any that already existed from an
  -- earlier chunk/run, so a resumed job converges on a fully subscribed set.
  -- The two legs are not interchangeable: a data-modifying CTE's inserts are
  -- invisible to sibling CTEs (they read the pre-statement snapshot), so the
  -- new rows have to come from RETURNING rather than from a re-select.
  resolved AS (
    SELECT id, email FROM inserted
    UNION
    SELECT p.id, p.email
    FROM public.people p
    JOIN dedup d ON d.email = lower(p.email)
    WHERE p.acquisition_source = 'send_testing'
  ),
  subscribed AS (
    INSERT INTO public.list_subscriptions (list_id, person_id, email, subscribed, source)
    SELECT p_list_id, r.id, r.email, true, 'send_testing'
    FROM resolved r
    ON CONFLICT (list_id, email) DO NOTHING
    RETURNING 1
  )
  SELECT
    (SELECT count(*) FROM inserted),
    (SELECT count(*) FROM subscribed)
  INTO v_created, v_subbed;

  RETURN jsonb_build_object('created', v_created, 'subscribed', v_subbed);
END;
$$;

-- 2. Current population size ---------------------------------------------------
CREATE OR REPLACE FUNCTION public.send_test_population_count(p_domain text)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
STABLE
AS $$
DECLARE
  v_domain text := public.send_test_assert_domain(p_domain);
  v_count  integer;
BEGIN
  PERFORM public.send_test_assert_caller();

  SELECT count(*)::integer INTO v_count
  FROM public.people
  WHERE acquisition_source = 'send_testing'
    AND email LIKE '%@' || v_domain;

  RETURN v_count;
END;
$$;

-- 3. Deprovision ---------------------------------------------------------------
-- p_keep_count NULL deletes the whole synthetic population; otherwise the
-- highest sequence numbers go first, so surviving addresses stay stable across
-- shrinks and past runs remain comparable.
CREATE OR REPLACE FUNCTION public.send_test_deprovision(
  p_domain     text,
  p_keep_count integer DEFAULT NULL
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_domain  text := public.send_test_assert_domain(p_domain);
  v_deleted integer := 0;
BEGIN
  PERFORM public.send_test_assert_caller();

  WITH doomed AS (
    SELECT p.id
    FROM public.people p
    WHERE p.acquisition_source = 'send_testing'
      AND p.email LIKE '%@' || v_domain
    ORDER BY p.email DESC
    LIMIT CASE
      WHEN p_keep_count IS NULL THEN NULL
      ELSE GREATEST(
        (SELECT count(*) FROM public.people
          WHERE acquisition_source = 'send_testing'
            AND email LIKE '%@' || v_domain) - p_keep_count,
        0)
    END
  ),
  gone AS (
    DELETE FROM public.people p
    USING doomed d
    WHERE p.id = d.id
    RETURNING 1
  )
  SELECT count(*) FROM gone INTO v_deleted;

  RETURN jsonb_build_object('deleted', v_deleted);
END;
$$;

-- 4. Reset subscriptions --------------------------------------------------------
-- Deliberately a separate, explicitly-invoked function rather than something on
-- a schedule: an unsubscribe performed from the inbox view (§4.5a) is a
-- deliberate test, and silently re-subscribing would undo it mid-verification.
CREATE OR REPLACE FUNCTION public.send_test_resubscribe(
  p_domain  text,
  p_list_id uuid
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_domain  text := public.send_test_assert_domain(p_domain);
  v_updated integer := 0;
BEGIN
  PERFORM public.send_test_assert_caller();

  WITH restored AS (
    UPDATE public.list_subscriptions ls
    SET subscribed = true, unsubscribed_at = NULL
    WHERE ls.list_id = p_list_id
      AND ls.email LIKE '%@' || v_domain
      AND ls.subscribed = false
    RETURNING 1
  )
  SELECT count(*) FROM restored INTO v_updated;

  RETURN jsonb_build_object('resubscribed', v_updated);
END;
$$;

-- 5. Attribution ------------------------------------------------------------------
-- Post-facto: claims unattributed arrivals inside the run's window, optionally
-- narrowed by a subject substring. Idempotent and re-runnable, which is what
-- lets a late straggler be folded in later without double-counting.
CREATE OR REPLACE FUNCTION public.send_test_attribute_run(p_run_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_run       public.send_test_runs%ROWTYPE;
  v_attributed integer := 0;
BEGIN
  PERFORM public.send_test_assert_caller();

  SELECT * INTO v_run FROM public.send_test_runs WHERE id = p_run_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'send-testing: run % not found', p_run_id;
  END IF;

  WITH claimed AS (
    UPDATE public.send_test_arrivals a
    SET run_id = v_run.id
    WHERE a.run_id IS NULL
      AND a.received_at >= v_run.started_at
      AND a.received_at <= COALESCE(v_run.closed_at, now())
      AND (
        v_run.subject_filter IS NULL
        OR v_run.subject_filter = ''
        OR a.subject ILIKE '%' || v_run.subject_filter || '%'
      )
    RETURNING 1
  )
  SELECT count(*) FROM claimed INTO v_attributed;

  RETURN jsonb_build_object('attributed', v_attributed);
END;
$$;

-- 6. Grants ---------------------------------------------------------------------
-- service_role ONLY. The admin app never calls these directly; it goes through
-- this module's Express routes, which authenticate the admin and then use the
-- service client. Granting `authenticated` here would hand every logged-in user
-- a PostgREST path straight past that middleware.
REVOKE ALL ON FUNCTION public.send_test_provision_batch(jsonb, text, uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.send_test_population_count(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.send_test_deprovision(text, integer) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.send_test_resubscribe(text, uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.send_test_attribute_run(uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.send_test_assert_caller() FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.send_test_provision_batch(jsonb, text, uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.send_test_population_count(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.send_test_deprovision(text, integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.send_test_resubscribe(text, uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.send_test_attribute_run(uuid) TO service_role;

COMMENT ON FUNCTION public.send_test_provision_batch(jsonb, text, uuid) IS
  'Creates one chunk of synthetic send-test people and subscribes them to the test list. Hard-limited to the configured test domain; cannot touch real people.';
COMMENT ON FUNCTION public.send_test_deprovision(text, integer) IS
  'Deletes synthetic send-test people (all, or shrink-to-count highest-sequence-first). Double-filtered on acquisition_source and test domain.';
COMMENT ON FUNCTION public.send_test_attribute_run(uuid) IS
  'Post-facto attribution of unattributed arrivals to a run by time window (+ optional subject filter). Idempotent; safe to re-run for late arrivals.';
