/**
 * emitNextjsRoutes — generate `app/<slug>/page.tsx` files for blocks-mode
 * pages, written to the publish branch alongside content/pages/<slug>.json.
 *
 * Per spec-content-modules-git-architecture §8.4 + §10.3:
 *   - For each blocks-mode page: emit a Server Component that imports
 *     the components per `component_export_path` and renders them
 *     with the saved props from content/pages/<slug>.json.
 *   - For pages with a wrapper_id assigned, emit `app/(<wrapper-name>)/<slug>/page.tsx`
 *     (Next.js route group syntax) so the page wrapper's
 *     `theme/app/(<wrapper-name>)/layout.tsx` applies.
 *   - Schema-mode pages: NOT emitted — the theme owns those route files
 *     in `main`; gatewaze just merges them through to publish.
 *   - Site wrapper: emit `theme/app/layout.tsx` for blocks-mode sites
 *     that import the site-level wrapper component.
 *
 * Returns the same Map<path, contents> that buildSiteContentFiles
 * returns, additive to the content/*.json files.
 */

interface BlocksPagePayload {
  slug: string;
  full_path: string;
  composition_mode: 'blocks';
  blocks: Array<{
    block_def_name: string;
    component_export_path: string | null;
    sort_order: number;
    content: Record<string, unknown>;
  }>;
}

interface WrapperRow {
  id: string;
  name: string;
  role: 'site' | 'page';
  component_export_path: string | null;
}

export interface EmitRoutesDeps {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  supabase: { from(table: string): any };
  /** Site row — needed for wrapper_id resolution. */
  site: {
    id: string;
    wrapper_id: string | null;
  };
  logger: {
    info: (msg: string, meta?: Record<string, unknown>) => void;
    warn: (msg: string, meta?: Record<string, unknown>) => void;
  };
}

export interface PageWithWrapper {
  slug: string;
  full_path: string;
  wrapper_id: string | null;
  composition_mode: 'schema' | 'blocks';
}

/**
 * Build the file map of generated app/* route files.
 *
 * Caller merges this with the content/* files from buildSiteContentFiles
 * before passing to publishCommit.
 */
export async function emitNextjsRoutes(
  pages: PageWithWrapper[],
  deps: EmitRoutesDeps,
): Promise<Map<string, string>> {
  const files = new Map<string, string>();

  // Resolve wrappers (site-level + every assigned page-level)
  const wrapperIds = new Set<string>();
  if (deps.site.wrapper_id) wrapperIds.add(deps.site.wrapper_id);
  for (const p of pages) if (p.wrapper_id) wrapperIds.add(p.wrapper_id);

  const wrappersById = new Map<string, WrapperRow>();
  if (wrapperIds.size > 0) {
    const result = await deps.supabase
      .from('templates_wrappers')
      .select('id, name, role, component_export_path')
      .in('id', [...wrapperIds]);
    const rows = ((result as { data: WrapperRow[] | null }).data ?? []);
    for (const row of rows) wrappersById.set(row.id, row);
  }

  const siteWrapper = deps.site.wrapper_id ? wrappersById.get(deps.site.wrapper_id) : null;

  // 1. Site-level layout (only when there's a site wrapper AND at least one
  //    blocks-mode page — schema-mode pages keep their theme's layout)
  const blocksPages = pages.filter((p) => p.composition_mode === 'blocks');
  if (blocksPages.length > 0 && siteWrapper && siteWrapper.component_export_path) {
    files.set('app/layout.tsx', emitSiteLayout(siteWrapper));
  }

  // 2. Per-page route files for blocks-mode pages
  for (const page of blocksPages) {
    const pageWrapper = page.wrapper_id ? wrappersById.get(page.wrapper_id) : null;

    // Route group syntax for page wrappers
    const routePath = pageWrapper && pageWrapper.role === 'page'
      ? `app/(${pageWrapper.name})${page.full_path === '/' ? '/(home)' : page.full_path}/page.tsx`
      : `app${page.full_path === '/' ? '/(home)' : page.full_path}/page.tsx`;

    files.set(routePath, emitBlocksPage(page));

    // Also emit a per-route-group layout if the page wrapper exists and we
    // haven't yet emitted one for this group
    if (pageWrapper && pageWrapper.role === 'page' && pageWrapper.component_export_path) {
      const layoutPath = `app/(${pageWrapper.name})/layout.tsx`;
      if (!files.has(layoutPath)) {
        files.set(layoutPath, emitPageWrapperLayout(pageWrapper));
      }
    }
  }

  deps.logger.info('emit-nextjs-routes done', {
    blocksPagesCount: blocksPages.length,
    filesEmitted: files.size,
  });

  return files;
}

// ---------------------------------------------------------------------------
// Templates
// ---------------------------------------------------------------------------

function emitSiteLayout(siteWrapper: WrapperRow): string {
  const importPath = siteWrapper.component_export_path!.replace(/\.tsx?$/, '');
  return `// AUTO-GENERATED by gatewaze publish — do not edit
import type { ReactNode } from 'react';
import { SiteWrapper } from '${importPath}';
import './globals.css';

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <SiteWrapper>{children}</SiteWrapper>
      </body>
    </html>
  );
}
`;
}

function emitPageWrapperLayout(pageWrapper: WrapperRow): string {
  const importPath = pageWrapper.component_export_path!.replace(/\.tsx?$/, '');
  // Component export name — derive from the file path's basename, capitalized
  // (e.g. './wrappers/docs' → DocsWrapper). This matches the convention in
  // the boilerplate.
  const basename = importPath.split('/').pop() ?? 'Wrapper';
  const exportName = basename
    .split('-')
    .map((s) => s[0]?.toUpperCase() + s.slice(1))
    .join('') + (basename.endsWith('Wrapper') ? '' : 'Wrapper');

  return `// AUTO-GENERATED by gatewaze publish — do not edit
import type { ReactNode } from 'react';
import { ${exportName} } from '${importPath}';

export default function GroupLayout({ children }: { children: ReactNode }) {
  return <${exportName}>{children}</${exportName}>;
}
`;
}

function emitBlocksPage(page: PageWithWrapper): string {
  // Read content from the sibling content/pages/<slug>.json file.
  // Each block is rendered via its component_export_path import + saved props.
  // Imports are deduplicated.
  const contentPath = `@/content/pages/${page.slug}.json`;
  return `// AUTO-GENERATED by gatewaze publish — do not edit
// Renders blocks-mode page from content/pages/${page.slug}.json
import content from '${contentPath}';

interface BlockInstance {
  block_def_name: string;
  component_export_path: string | null;
  sort_order: number;
  content: Record<string, unknown>;
}

interface PageContent {
  slug: string;
  full_path: string;
  composition_mode: 'blocks';
  blocks: BlockInstance[];
}

export default async function BlocksPage() {
  const data = content as PageContent;
  // Dynamic component imports: resolved at build time by Next.js + Turbopack.
  // Each block's component_export_path is relative to the theme repo root.
  const rendered = await Promise.all(
    data.blocks.map(async (block, idx) => {
      if (!block.component_export_path) return null;
      const mod = await import(/* webpackInclude: /\\.tsx$/ */ \`@/\${block.component_export_path.replace(/^\\.\\//, '')}\`);
      const Component = mod[block.block_def_name] ?? mod.default;
      if (!Component) return null;
      return <Component key={idx} {...block.content} />;
    }),
  );
  return <>{rendered}</>;
}
`;
}
