#!/usr/bin/env -S tsx
/**
 * One-shot script: run the TSX decomposer over every TSX file in
 * `gatewaze-template-email/emails/` and emit a TS module containing
 * the decomposed trees so the editor's starter-template picker can
 * ship them without a runtime parser dependency.
 *
 * Run this whenever the boilerplate's TSX files change:
 *
 *   pnpm dlx tsx modules/newsletters/admin/components/puck/tsx-decomposer/build-barebone-trees.ts \
 *     --src /Users/dan/Git/gatewaze/gatewaze-template-email/emails \
 *     --out modules/newsletters/admin/components/puck/starter-templates/barebone-trees.generated.ts
 */
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { resolve, basename, extname, join } from 'node:path';
import { decomposeBareboneTsx, type RegistryTreeEntry } from './parse.js';

interface Entry {
  slug: string;
  label: string;
  description: string;
  category: 'Onboarding' | 'Marketing' | 'Transactional' | 'Plain';
  blocks: RegistryTreeEntry[];
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  if (!args.src || !args.out) {
    console.error('usage: build-barebone-trees.ts --src <emails dir> --out <ts file>');
    process.exit(2);
  }

  const srcDir = resolve(args.src);
  const outFile = resolve(args.out);

  const files = (await readdir(srcDir)).filter(
    (f) => extname(f) === '.tsx' && !f.startsWith('theme'),
  );
  files.sort();

  const banner = `/**
 * AUTO-GENERATED — do not edit by hand.
 *
 * Generated by tsx-decomposer/build-barebone-trees.ts from the
 * Barebone TSX templates in gatewaze-template-email/emails/. Re-run
 * the script whenever the boilerplate's templates change.
 */
import type { StarterTemplate } from './index.js';
`;

  const entries: Entry[] = [];
  for (const f of files) {
    const full = join(srcDir, f);
    const src = await readFile(full, 'utf8');
    const { blocks, warnings } = decomposeBareboneTsx(src);
    if (warnings.length > 0) {
      console.warn(`[${f}] ${warnings.length} warning(s):`);
      for (const w of warnings) console.warn(`  - ${w}`);
    }
    const slug = basename(f, '.tsx');
    const label = humanise(slug);
    const cat = inferCategory(slug);
    entries.push({ slug, label, description: cat.description, category: cat.category, blocks });
  }

  const body = `export const BAREBONE_STARTER_TEMPLATES: ReadonlyArray<StarterTemplate> = ${
    JSON.stringify(
      entries.map((e) => ({
        slug: `barebone-${e.slug}`,
        label: `${e.label} (Barebone)`,
        description: e.description,
        category: e.category,
        blocks: e.blocks.map((b) => stripIds(b)),
      })),
      null,
      2,
    )
  } as const;
`;

  await writeFile(outFile, `${banner}\n${body}\n`, 'utf8');
  console.log(`wrote ${entries.length} barebone trees → ${outFile}`);
}

function stripIds(node: RegistryTreeEntry): RegistryTreeEntry {
  const props: Record<string, unknown> = { ...node.props };
  delete props.id;
  if (Array.isArray(props.children)) {
    props.children = (props.children as RegistryTreeEntry[]).map((c) => stripIds(c));
  }
  return { type: node.type, props };
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});

function humanise(slug: string): string {
  return slug
    .split('-')
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join(' ');
}

function inferCategory(slug: string): { category: Entry['category']; description: string } {
  if (slug.startsWith('welcome')) return { category: 'Onboarding', description: 'Welcome email — full layout with hero, features, and CTA cards.' };
  if (slug.startsWith('activation') || slug.startsWith('password')) return { category: 'Transactional', description: 'Transactional email — single-button confirmation.' };
  if (slug.startsWith('subscription')) return { category: 'Transactional', description: 'Subscription transactional email.' };
  if (slug.startsWith('feature') || slug.startsWith('product')) return { category: 'Marketing', description: 'Marketing email — feature / product update.' };
  return { category: 'Plain', description: 'Plain text-led email.' };
}

function parseArgs(argv: string[]): { src?: string; out?: string } {
  const out: { src?: string; out?: string } = {};
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--src') out.src = argv[++i];
    else if (argv[i] === '--out') out.out = argv[++i];
  }
  return out;
}
